"""empty message

Revision ID: f4dc83425f57
Revises: 0ff9588f620c
Create Date: 2023-03-18 16:36:58.402115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4dc83425f57'
down_revision = '0ff9588f620c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.alter_column('cadence',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('end_date',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.alter_column('end_date',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('cadence',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###