"""empty message

Revision ID: 564773132c3b
Revises: f4dc83425f57
Create Date: 2023-03-28 17:41:31.494450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '564773132c3b'
down_revision = 'f4dc83425f57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_complete', sa.Boolean(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timezone', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('timezone')

    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.drop_column('is_complete')

    # ### end Alembic commands ###